pipeline {
  agent any
  tools {
     maven 'M3'
    }
    stages {
      stage ('Initialization') {
        steps {
        sh '''
          echo "PATH =${PATH}"
          echo "M2_HOME = ${M2_HOME}"
          '''
        }
      }
        stage('Build') {
          steps {
               sh 'mvn clean package'
            }
          }
    }

} 
