pipeline {
  agent any
  tools {
    maven: 'M2'
     }
    stages {
      stage ('Initialization') {
        steps {
        sh '''
          echo "PATH =${PATH}"
             '''
        }
      }
        stage('Build') {
          steps {
                sh 'mvn clean package'
            }
          }
    }

} 
